---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmanager

spec:
  replicas: 1
  version: 4.4.9 # 4.2.15
  jvmParameters: ["-Xms2560m", "-Xmx2560m"] # 2.5M is a good size for docker-desktop -- comment out for larger clusters in production
  adminCredentials: admin-user-credentials # Should match metadata.name in the Kubernetes secret for the admin user
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            key1: value1
        spec:
          containers:
            - name: mongodb-ops-manager
              resources:
                limits:
                  cpu: "1.0"  # "2.0"
                  memory: 3Gi # 3Gi a good size for docker-desktop - 5GB or more is better for larger clusters in production

  externalConnectivity:
    type: LoadBalancer
    # type: NodePort # good for mini-kube (or where loadbalancer is not implemented)
    # port: 32080

  applicationDatabase:
    members: 3
    version: 4.2.8-ent
    persistent: true
    podSpec:
      cpu: "0.5"
      memory: 500Mi # 1Gi
      storage: 1Gi  # 2Gi
 
  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.adminEmailAddr: thomas.luckenbach@mongodb.com
    mms.fromEmailAddr: thomas.luckenbach@mongodb.com
    mms.mail.hostname: smtp-svc.mongodb.svc.cluster.local
    mms.mail.port: "25"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.replyToEmailAddr: thomas.luckenbach@mongodb.com
    mms.user.bypassInviteForExistingUsers: "true"
    mms.publicApi.whitelistEnabled: "false"
    automation.versions.source: mongodb # hybrid
    # brs.queryable.pem: /opt/mongodb/mms/secrets/queryable-backup.pem # stored in a secret
    brs.queryable.expiration: "3600000"
    mongodb.release.autoDownload.enterprise: "true"
    mongodb.release.modulePreference: enterpriseRequired

  backup:
    enabled: true
    jvmParameters: ["-Xms1024m", "-Xmx1024m"] # 1M is a good size for docker-desktop -- comment out for larger clusters in production
    opLogStores:
      - name: oplog
        mongodbResourceRef:
          name: ops-mgr-oplog
        mongodbUserRef:
          name: dbadmin-ops-mgr-oplog
    blockStores:
      - name: blockstore
        mongodbResourceRef:
          name: ops-mgr-blockstore
        mongodbUserRef:
          name: dbadmin-ops-mgr-blockstore
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongodb-backup-daemon
                resources:
                  requests:
                    cpu: "0.5"
                    memory: 1.2Gi # 1.2Gi is good size for docker-desktop -- use 5.0Gi is better for larger clusters in production
