---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: dbadmin-NAME
spec:
  passwordSecretKeyRef:
    name: dbadmin-NAME # Match to metadata.name of the User Secret
    key: password
  username: "dbAdmin"
  db: "admin" #
  mongodbResourceRef:
    name: "NAME" # Match to MongoDB resource using authenticaiton
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWriteAnyDatabase"
    - db: "admin"
      name: "dbAdminAnyDatabase"

